
""" Splitting the text based on the strategy"""
from typing import List
import tiktoken


class ChunkingService:
    @staticmethod
    def fixed_character_chunking(text: str, chunk_size: int = 1000, chunk_overlap: int = 200) -> List[str]:
        """splits the text by character length

        Args:
            text (str): text of the  file
            chunk_size (int, optional): number of vector chunks Defaults to 1000.
            chunk_overlap (int, optional): overlapping value. Defaults to 200.

        Returns:
            List[str]: an array of text
        """
        chunks = []
        start = 0

        while start < len(text):
            end = start + chunk_size
            chunks.append(text[start:end])
            start += (chunk_size - chunk_overlap)

        print(f"Chunks: {chunks}")
        return chunks

    @staticmethod
    def token_chunking(text: str, model_name:  str = "gpt-5.2", max_token: int = 256, overlap_tokens: int = 30) -> List[str]:
        """splits the text by acutal LLM tokens 

        Args:
            text (str): text of the  file
            model_name (str, optional): model name of any GenAI. Defaults to "gpt-5.2".
            max_token (int, optional): number of vector chunks. Defaults to 256.
            overlap_tokens (int, optional): overlapping tokens value. Defaults to 30.

        Returns:
            List[str]: a list of text generated by model
        """

        tokenizer = tiktoken.encoding_for_model(model_name)
        print(f"Tokenizer: {tokenizer}")

        tokens = tokenizer.encode(text)
        print("Tokens: ", tokens)

        start = 0
        chunks = []

        while start < len(text):
            end = start + max_token
            chunk_tokens = tokens[start:end]
            chunks.append(tokenizer.decode(chunk_tokens))
            start += (max_token - overlap_tokens)

        return chunks

    @staticmethod
    def chunk_document(cls, text: str, strategy: str) -> List[str]:
        if strategy == 'fixed':
            return cls.fixed_character_chunking(text)
        elif strategy == 'semantic':
            return cls.token_chunking(text)
        else:
            raise ValueError(f"Unkown chunking strategy: {strategy}")
